# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'roachWindow.ui'
#
# Created: Fri Aug 28 09:21:50 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(750, 762)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self._initRoachButton = QtGui.QPushButton(self.centralwidget)
        self._initRoachButton.setEnabled(False)
        self._initRoachButton.setGeometry(QtCore.QRect(30, 620, 391, 91))
        self._initRoachButton.setObjectName(_fromUtf8("_initRoachButton"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(460, 160, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_33 = QtGui.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(460, 190, 101, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self._tenGbEStatusLabel = QtGui.QLabel(self.centralwidget)
        self._tenGbEStatusLabel.setGeometry(QtCore.QRect(569, 190, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self._tenGbEStatusLabel.setFont(font)
        self._tenGbEStatusLabel.setObjectName(_fromUtf8("_tenGbEStatusLabel"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(460, 210, 211, 171))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.formLayout_7 = QtGui.QFormLayout(self.layoutWidget)
        self.formLayout_7.setMargin(0)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.label_17 = QtGui.QLabel(self.layoutWidget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_17)
        self._adc0OrLabel = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self._adc0OrLabel.setFont(font)
        self._adc0OrLabel.setObjectName(_fromUtf8("_adc0OrLabel"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self._adc0OrLabel)
        self.label_18 = QtGui.QLabel(self.layoutWidget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_18)
        self._adc1OrLabel = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self._adc1OrLabel.setFont(font)
        self._adc1OrLabel.setObjectName(_fromUtf8("_adc1OrLabel"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self._adc1OrLabel)
        self.label_19 = QtGui.QLabel(self.layoutWidget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_19)
        self._fft0OfLabel = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self._fft0OfLabel.setFont(font)
        self._fft0OfLabel.setObjectName(_fromUtf8("_fft0OfLabel"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.FieldRole, self._fft0OfLabel)
        self.label_20 = QtGui.QLabel(self.layoutWidget)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_20)
        self._fft1OfLabel = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self._fft1OfLabel.setFont(font)
        self._fft1OfLabel.setObjectName(_fromUtf8("_fft1OfLabel"))
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.FieldRole, self._fft1OfLabel)
        self.label_21 = QtGui.QLabel(self.layoutWidget)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_21)
        self._packetiserOfLabel = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self._packetiserOfLabel.setFont(font)
        self._packetiserOfLabel.setObjectName(_fromUtf8("_packetiserOfLabel"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.FieldRole, self._packetiserOfLabel)
        self.label_22 = QtGui.QLabel(self.layoutWidget)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_22)
        self._fifoOfLabel = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self._fifoOfLabel.setFont(font)
        self._fifoOfLabel.setObjectName(_fromUtf8("_fifoOfLabel"))
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.FieldRole, self._fifoOfLabel)
        self.label_23 = QtGui.QLabel(self.layoutWidget)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.formLayout_7.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_23)
        self._ethTxOfLabel = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self._ethTxOfLabel.setFont(font)
        self._ethTxOfLabel.setObjectName(_fromUtf8("_ethTxOfLabel"))
        self.formLayout_7.setWidget(6, QtGui.QFormLayout.FieldRole, self._ethTxOfLabel)
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(460, 390, 271, 104))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.formLayout_8 = QtGui.QFormLayout(self.layoutWidget1)
        self.formLayout_8.setMargin(0)
        self.formLayout_8.setObjectName(_fromUtf8("formLayout_8"))
        self.label_31 = QtGui.QLabel(self.layoutWidget1)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_31)
        self._clkFrequencyDisplay = QtGui.QLCDNumber(self.layoutWidget1)
        self._clkFrequencyDisplay.setObjectName(_fromUtf8("_clkFrequencyDisplay"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.FieldRole, self._clkFrequencyDisplay)
        self.label_32 = QtGui.QLabel(self.layoutWidget1)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_32)
        self._PPSCountDisplay = QtGui.QLCDNumber(self.layoutWidget1)
        self._PPSCountDisplay.setObjectName(_fromUtf8("_PPSCountDisplay"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.FieldRole, self._PPSCountDisplay)
        self.label_35 = QtGui.QLabel(self.layoutWidget1)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_35)
        self._hdf5FilenameLabel = QtGui.QLabel(self.layoutWidget1)
        self._hdf5FilenameLabel.setObjectName(_fromUtf8("_hdf5FilenameLabel"))
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.FieldRole, self._hdf5FilenameLabel)
        self.label_36 = QtGui.QLabel(self.layoutWidget1)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.formLayout_8.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_36)
        self._hdf5ProgressBar = QtGui.QProgressBar(self.layoutWidget1)
        self._hdf5ProgressBar.setProperty("value", 0)
        self._hdf5ProgressBar.setObjectName(_fromUtf8("_hdf5ProgressBar"))
        self.formLayout_8.setWidget(3, QtGui.QFormLayout.FieldRole, self._hdf5ProgressBar)
        self.layoutWidget2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 121, 401, 478))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label_13 = QtGui.QLabel(self.layoutWidget2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_13)
        self._channelSelectSpinbox = QtGui.QSpinBox(self.layoutWidget2)
        self._channelSelectSpinbox.setMaximum(255)
        self._channelSelectSpinbox.setProperty("value", 106)
        self._channelSelectSpinbox.setObjectName(_fromUtf8("_channelSelectSpinbox"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self._channelSelectSpinbox)
        self.gridLayout.addLayout(self.formLayout_6, 0, 0, 1, 1)
        self._channelUpdateButton = QtGui.QPushButton(self.layoutWidget2)
        self._channelUpdateButton.setEnabled(False)
        self._channelUpdateButton.setObjectName(_fromUtf8("_channelUpdateButton"))
        self.gridLayout.addWidget(self._channelUpdateButton, 0, 1, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label)
        self.label_2 = QtGui.QLabel(self.layoutWidget2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(self.layoutWidget2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self._destinationIPBox = QtGui.QLineEdit(self.layoutWidget2)
        self._destinationIPBox.setObjectName(_fromUtf8("_destinationIPBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self._destinationIPBox)
        self._destinationPortSpinbox = QtGui.QSpinBox(self.layoutWidget2)
        self._destinationPortSpinbox.setMaximum(65535)
        self._destinationPortSpinbox.setProperty("value", 60000)
        self._destinationPortSpinbox.setObjectName(_fromUtf8("_destinationPortSpinbox"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self._destinationPortSpinbox)
        self.gridLayout.addLayout(self.formLayout, 1, 0, 1, 1)
        self._tenGbeUpdateButton = QtGui.QPushButton(self.layoutWidget2)
        self._tenGbeUpdateButton.setEnabled(False)
        self._tenGbeUpdateButton.setObjectName(_fromUtf8("_tenGbeUpdateButton"))
        self.gridLayout.addWidget(self._tenGbeUpdateButton, 1, 1, 1, 1)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_4 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.layoutWidget2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.layoutWidget2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.layoutWidget2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_7)
        self._dataSizePerPacketSpinbox = QtGui.QSpinBox(self.layoutWidget2)
        self._dataSizePerPacketSpinbox.setMinimum(1)
        self._dataSizePerPacketSpinbox.setMaximum(8194)
        self._dataSizePerPacketSpinbox.setProperty("value", 1024)
        self._dataSizePerPacketSpinbox.setObjectName(_fromUtf8("_dataSizePerPacketSpinbox"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self._dataSizePerPacketSpinbox)
        self._interpacketLengthSpinbox = QtGui.QSpinBox(self.layoutWidget2)
        self._interpacketLengthSpinbox.setMinimum(0)
        self._interpacketLengthSpinbox.setMaximum(1024)
        self._interpacketLengthSpinbox.setProperty("value", 16)
        self._interpacketLengthSpinbox.setObjectName(_fromUtf8("_interpacketLengthSpinbox"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self._interpacketLengthSpinbox)
        self._packetsPerWindowLabel = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self._packetsPerWindowLabel.setFont(font)
        self._packetsPerWindowLabel.setObjectName(_fromUtf8("_packetsPerWindowLabel"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self._packetsPerWindowLabel)
        self.gridLayout.addLayout(self.formLayout_2, 2, 0, 1, 1)
        self._packetsUpdateButton = QtGui.QPushButton(self.layoutWidget2)
        self._packetsUpdateButton.setEnabled(False)
        self._packetsUpdateButton.setObjectName(_fromUtf8("_packetsUpdateButton"))
        self.gridLayout.addWidget(self._packetsUpdateButton, 2, 1, 1, 1)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_8 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label_8)
        self.label_9 = QtGui.QLabel(self.layoutWidget2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtGui.QLabel(self.layoutWidget2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtGui.QLabel(self.layoutWidget2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_11)
        self._fftShiftShiftbox = QtGui.QSpinBox(self.layoutWidget2)
        self._fftShiftShiftbox.setMinimum(0)
        self._fftShiftShiftbox.setMaximum(2047)
        self._fftShiftShiftbox.setProperty("value", 2047)
        self._fftShiftShiftbox.setObjectName(_fromUtf8("_fftShiftShiftbox"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self._fftShiftShiftbox)
        self._accumulationLengthSpinbox = QtGui.QSpinBox(self.layoutWidget2)
        self._accumulationLengthSpinbox.setMinimum(1)
        self._accumulationLengthSpinbox.setMaximum(10000)
        self._accumulationLengthSpinbox.setProperty("value", 3125)
        self._accumulationLengthSpinbox.setObjectName(_fromUtf8("_accumulationLengthSpinbox"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self._accumulationLengthSpinbox)
        self._adcAttenuationSpinbox = QtGui.QSpinBox(self.layoutWidget2)
        self._adcAttenuationSpinbox.setMinimum(0)
        self._adcAttenuationSpinbox.setMaximum(63)
        self._adcAttenuationSpinbox.setProperty("value", 10)
        self._adcAttenuationSpinbox.setObjectName(_fromUtf8("_adcAttenuationSpinbox"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self._adcAttenuationSpinbox)
        self.gridLayout.addLayout(self.formLayout_3, 3, 0, 1, 1)
        self._signalUpdateButton = QtGui.QPushButton(self.layoutWidget2)
        self._signalUpdateButton.setEnabled(False)
        self._signalUpdateButton.setObjectName(_fromUtf8("_signalUpdateButton"))
        self.gridLayout.addWidget(self._signalUpdateButton, 3, 1, 1, 1)
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_12 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_12)
        self._NDEnableCheckbox = QtGui.QCheckBox(self.layoutWidget2)
        self._NDEnableCheckbox.setObjectName(_fromUtf8("_NDEnableCheckbox"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self._NDEnableCheckbox)
        self._NDDutycycleModeCheckbox = QtGui.QCheckBox(self.layoutWidget2)
        self._NDDutycycleModeCheckbox.setObjectName(_fromUtf8("_NDDutycycleModeCheckbox"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self._NDDutycycleModeCheckbox)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_15 = QtGui.QLabel(self.layoutWidget2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtGui.QLabel(self.layoutWidget2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_16)
        self._NDHighTimeSpinbox = QtGui.QSpinBox(self.layoutWidget2)
        self._NDHighTimeSpinbox.setMinimum(0)
        self._NDHighTimeSpinbox.setMaximum(2147483647)
        self._NDHighTimeSpinbox.setProperty("value", 125)
        self._NDHighTimeSpinbox.setObjectName(_fromUtf8("_NDHighTimeSpinbox"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self._NDHighTimeSpinbox)
        self._NDLowTimeSpinbox = QtGui.QSpinBox(self.layoutWidget2)
        self._NDLowTimeSpinbox.setMinimum(0)
        self._NDLowTimeSpinbox.setMaximum(2147483647)
        self._NDLowTimeSpinbox.setSingleStep(1)
        self._NDLowTimeSpinbox.setProperty("value", 1250)
        self._NDLowTimeSpinbox.setObjectName(_fromUtf8("_NDLowTimeSpinbox"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self._NDLowTimeSpinbox)
        self._NDHighTimeLabel = QtGui.QLabel(self.layoutWidget2)
        self._NDHighTimeLabel.setObjectName(_fromUtf8("_NDHighTimeLabel"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self._NDHighTimeLabel)
        self._NDLowTimeLabel = QtGui.QLabel(self.layoutWidget2)
        self._NDLowTimeLabel.setObjectName(_fromUtf8("_NDLowTimeLabel"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self._NDLowTimeLabel)
        self.formLayout_5.setLayout(3, QtGui.QFormLayout.LabelRole, self.formLayout_4)
        self.gridLayout.addLayout(self.formLayout_5, 4, 0, 1, 1)
        self._NDUpdateButton = QtGui.QPushButton(self.layoutWidget2)
        self._NDUpdateButton.setEnabled(False)
        self._NDUpdateButton.setObjectName(_fromUtf8("_NDUpdateButton"))
        self.gridLayout.addWidget(self._NDUpdateButton, 4, 1, 1, 1)
        self.layoutWidget3 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(60, 10, 328, 105))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self._gatewareSelectCombo = QtGui.QComboBox(self.layoutWidget3)
        self._gatewareSelectCombo.setEnabled(False)
        self._gatewareSelectCombo.setObjectName(_fromUtf8("_gatewareSelectCombo"))
        self._gatewareSelectCombo.addItem(_fromUtf8(""))
        self._gatewareSelectCombo.addItem(_fromUtf8(""))
        self._gatewareSelectCombo.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self._gatewareSelectCombo, 2, 1, 1, 2)
        self.label_25 = QtGui.QLabel(self.layoutWidget3)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_2.addWidget(self.label_25, 1, 0, 1, 2)
        self._katcpPortSpinbox = QtGui.QSpinBox(self.layoutWidget3)
        self._katcpPortSpinbox.setMaximum(65535)
        self._katcpPortSpinbox.setProperty("value", 7147)
        self._katcpPortSpinbox.setObjectName(_fromUtf8("_katcpPortSpinbox"))
        self.gridLayout_2.addWidget(self._katcpPortSpinbox, 1, 2, 1, 1)
        self.label_26 = QtGui.QLabel(self.layoutWidget3)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_2.addWidget(self.label_26, 2, 0, 1, 1)
        self._roachHostIPBox = QtGui.QLineEdit(self.layoutWidget3)
        self._roachHostIPBox.setText(_fromUtf8(""))
        self._roachHostIPBox.setObjectName(_fromUtf8("_roachHostIPBox"))
        self.gridLayout_2.addWidget(self._roachHostIPBox, 0, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self.layoutWidget3)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_2.addWidget(self.label_24, 0, 0, 1, 2)
        self._connectToRoachButton = QtGui.QPushButton(self.centralwidget)
        self._connectToRoachButton.setEnabled(True)
        self._connectToRoachButton.setGeometry(QtCore.QRect(430, 20, 231, 91))
        self._connectToRoachButton.setObjectName(_fromUtf8("_connectToRoachButton"))
        self._manualResyncButton = QtGui.QPushButton(self.centralwidget)
        self._manualResyncButton.setEnabled(False)
        self._manualResyncButton.setGeometry(QtCore.QRect(480, 620, 231, 91))
        self._manualResyncButton.setObjectName(_fromUtf8("_manualResyncButton"))
        self._initRoachButton_2 = QtGui.QPushButton(self.centralwidget)
        self._initRoachButton_2.setEnabled(False)
        self._initRoachButton_2.setGeometry(QtCore.QRect(60, 1220, 391, 91))
        self._initRoachButton_2.setObjectName(_fromUtf8("_initRoachButton_2"))
        self.label_27 = QtGui.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(460, 570, 121, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self._timeLabel = QtGui.QLabel(self.centralwidget)
        self._timeLabel.setGeometry(QtCore.QRect(460, 590, 151, 16))
        self._timeLabel.setObjectName(_fromUtf8("_timeLabel"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "AVN ROACH Control", None))
        self._initRoachButton.setText(_translate("MainWindow", "Initialise ROACH and sync next PPS", None))
        self.label_14.setText(_translate("MainWindow", "Indicators:", None))
        self.label_33.setText(_translate("MainWindow", "10Gbe Status", None))
        self._tenGbEStatusLabel.setText(_translate("MainWindow", "--", None))
        self.label_17.setText(_translate("MainWindow", "ADC0 OR", None))
        self._adc0OrLabel.setText(_translate("MainWindow", "--", None))
        self.label_18.setText(_translate("MainWindow", "ADC1 OR", None))
        self._adc1OrLabel.setText(_translate("MainWindow", "--", None))
        self.label_19.setText(_translate("MainWindow", "FFT0 OF", None))
        self._fft0OfLabel.setText(_translate("MainWindow", "--", None))
        self.label_20.setText(_translate("MainWindow", "FFT1 OF", None))
        self._fft1OfLabel.setText(_translate("MainWindow", "--", None))
        self.label_21.setText(_translate("MainWindow", "Packetiser OF", None))
        self._packetiserOfLabel.setText(_translate("MainWindow", "--", None))
        self.label_22.setText(_translate("MainWindow", "FIFO OF", None))
        self._fifoOfLabel.setText(_translate("MainWindow", "--", None))
        self.label_23.setText(_translate("MainWindow", "Eth Tx OF", None))
        self._ethTxOfLabel.setText(_translate("MainWindow", "--", None))
        self.label_31.setText(_translate("MainWindow", "Clk Frequency", None))
        self.label_32.setText(_translate("MainWindow", "PPS Count", None))
        self.label_35.setText(_translate("MainWindow", "HDF5 Filename", None))
        self._hdf5FilenameLabel.setText(_translate("MainWindow", "--", None))
        self.label_36.setText(_translate("MainWindow", "HDF5 Progress", None))
        self.label_13.setText(_translate("MainWindow", "Channel: (Narrowband only)", None))
        self._channelUpdateButton.setText(_translate("MainWindow", "Update Channel", None))
        self.label.setText(_translate("MainWindow", "10GbE config:", None))
        self.label_2.setText(_translate("MainWindow", "Destination IP", None))
        self.label_3.setText(_translate("MainWindow", "Destination Port", None))
        self._destinationIPBox.setText(_translate("MainWindow", "10.0.0.3", None))
        self._tenGbeUpdateButton.setText(_translate("MainWindow", "Update 10GbE", None))
        self.label_4.setText(_translate("MainWindow", "Packet config:", None))
        self.label_5.setText(_translate("MainWindow", "Data size / packet", None))
        self.label_6.setText(_translate("MainWindow", "Interpacket length", None))
        self.label_7.setText(_translate("MainWindow", "Packets per window", None))
        self._packetsPerWindowLabel.setText(_translate("MainWindow", "--", None))
        self._packetsUpdateButton.setText(_translate("MainWindow", "Update Packets", None))
        self.label_8.setText(_translate("MainWindow", "Signal config:", None))
        self.label_9.setText(_translate("MainWindow", "FFT Shift", None))
        self.label_10.setText(_translate("MainWindow", "Accumulation Length", None))
        self.label_11.setText(_translate("MainWindow", "ADC Attenuation", None))
        self._signalUpdateButton.setText(_translate("MainWindow", "Update Signal", None))
        self.label_12.setText(_translate("MainWindow", "Noise Diode config:", None))
        self._NDEnableCheckbox.setText(_translate("MainWindow", "ND Enable", None))
        self._NDDutycycleModeCheckbox.setText(_translate("MainWindow", "ND Duty-cycle mode", None))
        self.label_15.setText(_translate("MainWindow", "High time", None))
        self.label_16.setText(_translate("MainWindow", "Low time", None))
        self._NDHighTimeLabel.setText(_translate("MainWindow", "time in seconds", None))
        self._NDLowTimeLabel.setText(_translate("MainWindow", "time in seconds", None))
        self._NDUpdateButton.setText(_translate("MainWindow", "Update Nose Diode", None))
        self._gatewareSelectCombo.setItemText(0, _translate("MainWindow", "Wideband Spectrometer", None))
        self._gatewareSelectCombo.setItemText(1, _translate("MainWindow", "Narrowband Spectrometer", None))
        self._gatewareSelectCombo.setItemText(2, _translate("MainWindow", "Time stream data", None))
        self.label_25.setText(_translate("MainWindow", "KATCP Port:", None))
        self.label_26.setText(_translate("MainWindow", "Gateware:", None))
        self.label_24.setText(_translate("MainWindow", "ROACH IP / Hostname:", None))
        self._connectToRoachButton.setText(_translate("MainWindow", "Connect to ROACH", None))
        self._manualResyncButton.setText(_translate("MainWindow", "Manual resync", None))
        self._initRoachButton_2.setText(_translate("MainWindow", "Initialise ROACH and sync next PPS", None))
        self.label_27.setText(_translate("MainWindow", "Current UNIX time:", None))
        self._timeLabel.setText(_translate("MainWindow", "time", None))

